source 'https://rubygems.org'
gem 'capybara'
gem 'nokogiri'
gem 'poltergeist'

gem 'pg'

gem "awesome_print"
gem "pry-stack_explorer"
gem "pry-byebug"
gem "pry-rescue"
gem "pry-doc"
gem "pry-docmore"
gem "binding_of_caller"

ruby "2.2.1"
